### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\Pictures'

### ISSUE THREAD

**Issue by RasoKO** [argosk/encrypt#2]
Hello im getting permission error when i do that:

![image](https://user-images.githubusercontent.com/73038021/136099684-089c176c-ba4f-4448-9e89-4183ec3ae2b4.png)

**Comment by argosk** [comment]
The PermissionError: [errno 13] permission denied error occurs when you try to access a file from Python without having the necessary permissions. To fix this error, use the chmod or chown command to change the permissions of the file so that the right user and/or group can access the file.
